// Import tests (M4, #15): approved batches import, select, and roll back
// through the versioned manifest; rejected items never enter; nothing is
// silently repaired; a bad import can never brick rollback.

import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { importBatch, rollbackManifest } from "./import-question-batch.mjs";
import { writeBatch } from "./generate-question-batch.mjs";
import { FULL_REVIEW_QUOTA, planReview } from "./review-question-batch.mjs";
import {
  parseActiveManifestPointer,
  parseQuestionBankManifest,
  resolveManifestEntry,
  verifyManifestEntryAgainstBank,
} from "../shared/question-bank-manifest.ts";
import { parseQuestionBankData } from "../shared/question-bank-validate.ts";

const GEN = { topic: "4.2", tpMin: 2, tpMax: 3, profile: "dpk3_2026_core", count: 12 };

/** A scratch resources tree with one routed v2 bank (bankA v1, topic 4.2 TP2–3). */
async function makeTree() {
  const dir = await mkdtemp(join(tmpdir(), "import-"));
  const resourcesDir = join(dir, "resources");
  const docsDir = join(dir, "docs");
  const candidatesDir = join(dir, "candidates");
  const ledgerPath = join(dir, "ledger.json");
  await mkdir(join(resourcesDir, "question-banks", "std1"), { recursive: true });

  // Base routed bank: generated by the real generator, so it is gate-clean.
  const base = await writeBatch(
    { bankId: "std1.bank-a", ...GEN, seed: 101 },
    { candidatesDir, resourcesDir },
  );
  await writeFile(join(resourcesDir, "question-banks", "std1", "std1.bank-a.v1.json"), await readFile(base.candidatePath, "utf8"));
  const manifest = {
    schema_version: 1,
    manifest_id: "std1-question-banks",
    version: 1,
    source: "test fixture",
    entries: [
      {
        grade: "std1",
        topic: "4.2",
        tp_min: 2,
        tp_max: 3,
        profile: "dpk3_2026_core",
        bank_id: "std1.bank-a",
        version: 1,
        path: "question-banks/std1/std1.bank-a.v1",
      },
    ],
  };
  await writeFile(join(resourcesDir, "question-banks", "manifest.v1.json"), JSON.stringify(manifest, null, 2) + "\n");
  await writeFile(
    join(resourcesDir, "question-banks", "active-manifest.json"),
    JSON.stringify({ schema_version: 1, manifest: "question-banks/manifest.v1" }, null, 2) + "\n",
  );
  await writeFile(
    ledgerPath,
    JSON.stringify({ schema_version: 1, full_review_quota: FULL_REVIEW_QUOTA, sample_rate: 0.05, reviewed_total: 20, history: [] }),
  );
  return { dir, resourcesDir, docsDir, candidatesDir, ledgerPath };
}

async function readJson(path) {
  return JSON.parse(await readFile(path, "utf8"));
}

/** Generate a candidate and a complete decisions file approving it. */
async function staged(tree, { seed, bankId, rejected = [], tamper = null }) {
  const { candidatePath } = await writeBatch(
    { bankId, ...GEN, seed },
    { candidatesDir: tree.candidatesDir, resourcesDir: tree.resourcesDir },
  );
  let text = await readFile(candidatePath, "utf8");
  if (tamper) {
    const batch = tamper(JSON.parse(text));
    text = JSON.stringify(batch, null, 2) + "\n";
    await writeFile(candidatePath, text);
  }
  const batch = JSON.parse(text);
  const { createHash } = await import("node:crypto");
  const decisions = {
    schema_version: 1,
    batch: candidatePath.split("/").pop(),
    batch_sha256: createHash("sha256").update(text).digest("hex"),
    mode: "full",
    required_ids: batch.questions.map((q) => q.id),
    reviewer: "season",
    reviewed_at: "2026-07-19T00:00:00.000Z",
    reviewed: batch.questions.map((q) => q.id),
    rejected,
  };
  const decisionsPath = join(tree.dir, `decisions-${seed}.json`);
  await writeFile(decisionsPath, JSON.stringify(decisions, null, 2) + "\n");
  return { candidatePath, decisionsPath, batch };
}

const opts = (tree, extra = {}) => ({
  resourcesDir: tree.resourcesDir,
  docsDir: tree.docsDir,
  ledgerPath: tree.ledgerPath,
  ...extra,
});

test("import: new bank end-to-end — bank, manifest, pointer, ledger, gate evidence", async () => {
  const tree = await makeTree();
  try {
    // Topic 4.1 TP1–2 does not overlap the fixture's 4.2 TP2–3 route.
    const { candidatePath } = await writeBatch(
      { bankId: "std1.bank-b", topic: "4.1", tpMin: 1, tpMax: 2, profile: "dpk3_2026_core", count: 12, seed: 202 },
      { candidatesDir: tree.candidatesDir, resourcesDir: tree.resourcesDir },
    );
    const text = await readFile(candidatePath, "utf8");
    const batch = JSON.parse(text);
    const { createHash } = await import("node:crypto");
    const decisions = {
      schema_version: 1,
      batch: candidatePath.split("/").pop(),
      batch_sha256: createHash("sha256").update(text).digest("hex"),
      mode: "full",
      required_ids: batch.questions.map((q) => q.id),
      reviewer: "season",
      reviewed_at: "2026-07-19T00:00:00.000Z",
      reviewed: batch.questions.map((q) => q.id),
      rejected: [],
    };
    const decisionsPath = join(tree.dir, "decisions-202.json");
    await writeFile(decisionsPath, JSON.stringify(decisions, null, 2) + "\n");

    const result = await importBatch(candidatePath, decisionsPath, opts(tree, { activate: true }));
    assert.equal(result.mode, "new-bank");
    assert.equal(result.bankVersion, 1);
    assert.equal(result.manifestVersion, 2);
    assert.equal(result.gateAccept, true);

    // The whole chain re-validates from disk: pointer → manifest → resolve → verify.
    const pointer = parseActiveManifestPointer(await readJson(join(tree.resourcesDir, "question-banks", "active-manifest.json")));
    assert.equal(pointer.manifest, "question-banks/manifest.v2");
    const manifest = parseQuestionBankManifest(await readJson(join(tree.resourcesDir, "question-banks", "manifest.v2.json")));
    assert.equal(manifest.entries.length, 2);
    const entry = resolveManifestEntry(manifest, { grade: "std1", topic: "4.1", profile: "dpk3_2026_core", tpLevel: 1 });
    const bank = parseQuestionBankData(await readJson(join(tree.resourcesDir, `${entry.path}.json`)));
    verifyManifestEntryAgainstBank(entry, bank);
    assert.equal(bank.questions.length, 12);

    // Cocos meta companions exist; the ledger recorded the import; gate evidence shipped.
    await readJson(join(tree.resourcesDir, "question-banks", "std1", "std1.bank-b.v1.json.meta"));
    await readJson(join(tree.resourcesDir, "question-banks", "manifest.v2.json.meta"));
    const ledger = await readJson(tree.ledgerPath);
    assert.equal(ledger.reviewed_total, 20 + 12);
    assert.equal(ledger.history.at(-1).activated, true);
    const evidence = await readFile(join(tree.docsDir, "std1.bank-b.v1.gate.md"), "utf8");
    assert.match(evidence, /✅ ACCEPT/);
  } finally {
    await rm(tree.dir, { recursive: true, force: true });
  }
});

test("import: an overlapping route is rejected before anything is written (rollback stays safe)", async () => {
  const tree = await makeTree();
  try {
    // bank-b targets the SAME slice as the fixture's bank-a route.
    const { candidatePath, decisionsPath } = await staged(tree, { seed: 202, bankId: "std1.bank-b" });
    await assert.rejects(importBatch(candidatePath, decisionsPath, opts(tree, { activate: true })), /routes must not overlap/);
    const pointer = parseActiveManifestPointer(await readJson(join(tree.resourcesDir, "question-banks", "active-manifest.json")));
    assert.equal(pointer.manifest, "question-banks/manifest.v1");
    await assert.rejects(readJson(join(tree.resourcesDir, "question-banks", "manifest.v2.json")), /ENOENT/);
    await assert.rejects(readJson(join(tree.resourcesDir, "question-banks", "std1", "std1.bank-b.v1.json")), /ENOENT/);
  } finally {
    await rm(tree.dir, { recursive: true, force: true });
  }
});

test("import: merge appends approved questions with fresh ids and bumps the route", async () => {
  const tree = await makeTree();
  try {
    const { candidatePath, decisionsPath } = await staged(tree, {
      seed: 303,
      bankId: "std1.bank-a",
      rejected: [{ id: 2, reason: "wording too hard" }, { id: 5, reason: "distractor too close" }],
    });
    const result = await importBatch(candidatePath, decisionsPath, opts(tree, { activate: true }));
    assert.equal(result.mode, "merge");
    assert.equal(result.bankVersion, 2);
    assert.equal(result.approved, 10);
    assert.equal(result.rejected, 2);

    const bank = parseQuestionBankData(await readJson(join(tree.resourcesDir, "question-banks", "std1", "std1.bank-a.v2.json")));
    const base = parseQuestionBankData(await readJson(join(tree.resourcesDir, "question-banks", "std1", "std1.bank-a.v1.json")));
    assert.equal(bank.questions.length, base.questions.length + 10);
    // Base questions carried verbatim (same ids, same content — never repaired).
    for (const q of base.questions) {
      assert.deepEqual(bank.questions.find((x) => x.id === q.id), q);
    }
    // New ids continue from the base max; rejected candidate ids never entered.
    const newIds = bank.questions.slice(base.questions.length).map((q) => q.id);
    assert.deepEqual(newIds, Array.from({ length: 10 }, (_, i) => base.questions.length + 1 + i));

    const manifest = parseQuestionBankManifest(await readJson(join(tree.resourcesDir, "question-banks", "manifest.v2.json")));
    const entry = resolveManifestEntry(manifest, { grade: "std1", topic: "4.2", profile: "dpk3_2026_core", tpLevel: 3 });
    assert.equal(entry.version, 2);
    verifyManifestEntryAgainstBank(entry, bank);

    const ledger = await readJson(tree.ledgerPath);
    assert.equal(ledger.reviewed_total, 20 + 12);
    assert.equal(ledger.history.at(-1).bank_version, 2);
    assert.equal(ledger.history.at(-1).rejected.length, 2);
    assert.ok(ledger.history.at(-1).candidate_id_map);
  } finally {
    await rm(tree.dir, { recursive: true, force: true });
  }
});

test("import: disjoint TP band on the same bank_id is a new route, and later merges hit the right entry", async () => {
  const tree = await makeTree();
  try {
    // bank-a covers 4.2 TP2–3; a TP4 batch on the same bank_id is a disjoint slice.
    const disjoint = await writeBatch(
      { bankId: "std1.bank-a", topic: "4.2", tpMin: 4, tpMax: 4, profile: "dpk3_2026_core", count: 8, seed: 404 },
      { candidatesDir: tree.candidatesDir, resourcesDir: tree.resourcesDir },
    );
    const batch = await readJson(disjoint.candidatePath);
    const { createHash } = await import("node:crypto");
    const decisions = {
      schema_version: 1,
      batch: "d",
      batch_sha256: createHash("sha256").update(await readFile(disjoint.candidatePath, "utf8")).digest("hex"),
      mode: "full",
      required_ids: batch.questions.map((q) => q.id),
      reviewer: "season",
      reviewed_at: "2026-07-19T00:00:00.000Z",
      reviewed: batch.questions.map((q) => q.id),
      rejected: [],
    };
    const decisionsPath = join(tree.dir, "decisions-404.json");
    await writeFile(decisionsPath, JSON.stringify(decisions, null, 2) + "\n");

    const first = await importBatch(disjoint.candidatePath, decisionsPath, opts(tree, { activate: true }));
    assert.equal(first.mode, "new-route");
    assert.equal(first.bankVersion, 2);

    // Both routes resolve; the TP2–3 route still points at v1.
    const manifest = parseQuestionBankManifest(await readJson(join(tree.resourcesDir, "question-banks", "manifest.v2.json")));
    assert.equal(manifest.entries.length, 2);
    assert.equal(resolveManifestEntry(manifest, { grade: "std1", topic: "4.2", profile: "dpk3_2026_core", tpLevel: 2 }).version, 1);
    assert.equal(resolveManifestEntry(manifest, { grade: "std1", topic: "4.2", profile: "dpk3_2026_core", tpLevel: 4 }).version, 2);

    // A second TP4 batch merges into the TP4 route, not the TP2–3 one.
    const tp4 = await writeBatch(
      { bankId: "std1.bank-a", topic: "4.2", tpMin: 4, tpMax: 4, profile: "dpk3_2026_core", count: 6, seed: 405 },
      { candidatesDir: tree.candidatesDir, resourcesDir: tree.resourcesDir },
    );
    const tp4Batch = await readJson(tp4.candidatePath);
    const tp4Text = await readFile(tp4.candidatePath, "utf8");
    const tp4Decisions = {
      ...decisions,
      batch_sha256: createHash("sha256").update(tp4Text).digest("hex"),
      required_ids: tp4Batch.questions.map((q) => q.id),
      reviewed: tp4Batch.questions.map((q) => q.id),
    };
    const tp4DecisionsPath = join(tree.dir, "decisions-405.json");
    await writeFile(tp4DecisionsPath, JSON.stringify(tp4Decisions, null, 2) + "\n");
    const merged = await importBatch(tp4.candidatePath, tp4DecisionsPath, opts(tree, { activate: true }));
    assert.equal(merged.mode, "merge");
    assert.equal(merged.bankVersion, 3);
    const manifest3 = parseQuestionBankManifest(await readJson(join(tree.resourcesDir, "question-banks", "manifest.v3.json")));
    assert.equal(resolveManifestEntry(manifest3, { grade: "std1", topic: "4.2", profile: "dpk3_2026_core", tpLevel: 2 }).version, 1);
    assert.equal(resolveManifestEntry(manifest3, { grade: "std1", topic: "4.2", profile: "dpk3_2026_core", tpLevel: 4 }).version, 3);
  } finally {
    await rm(tree.dir, { recursive: true, force: true });
  }
});

test("import: refuses incomplete reviews, unknown ids, and unreviewed rejections", async () => {
  const tree = await makeTree();
  try {
    const { candidatePath, decisionsPath, batch } = await staged(tree, { seed: 505, bankId: "std1.bank-a" });
    const decisions = await readJson(decisionsPath);

    const short = { ...decisions, reviewed: decisions.reviewed.slice(1) };
    await writeFile(decisionsPath, JSON.stringify(short));
    await assert.rejects(importBatch(candidatePath, decisionsPath, opts(tree)), /review incomplete.*Q1/s);

    const unknown = { ...decisions, reviewed: [...decisions.reviewed, 999] };
    await writeFile(decisionsPath, JSON.stringify(unknown));
    await assert.rejects(importBatch(candidatePath, decisionsPath, opts(tree)), /unknown question id 999/);

    // Rejecting a question that was never reviewed: only reachable in sample
    // mode (in full mode every id is required, so coverage fails first).
    await writeFile(
      tree.ledgerPath,
      JSON.stringify({ schema_version: 1, full_review_quota: FULL_REVIEW_QUOTA, sample_rate: 0.05, reviewed_total: FULL_REVIEW_QUOTA, history: [] }),
    );
    const plan = await planReview(await readFile(candidatePath, "utf8"), tree.ledgerPath);
    const outside = batch.questions.map((q) => q.id).find((id) => !plan.requiredIds.includes(id));
    const unreviewedReject = { ...decisions, reviewed: plan.requiredIds, rejected: [{ id: outside, reason: "x" }] };
    await writeFile(decisionsPath, JSON.stringify(unreviewedReject));
    await assert.rejects(importBatch(candidatePath, decisionsPath, opts(tree)), /is rejected but was never reviewed/);

    const shaBroken = { ...decisions, batch_sha256: "0".repeat(64) };
    await writeFile(decisionsPath, JSON.stringify(shaBroken));
    await assert.rejects(importBatch(candidatePath, decisionsPath, opts(tree)), /sha256 mismatch/);
    assert.ok(batch.questions.length > 0);
  } finally {
    await rm(tree.dir, { recursive: true, force: true });
  }
});

test("import: a tampered batch fails the re-gate and nothing is written or repaired", async () => {
  const tree = await makeTree();
  try {
    const { candidatePath, decisionsPath } = await staged(tree, {
      seed: 606,
      bankId: "std1.bank-a",
      tamper: (batch) => {
        batch.questions[0].answer += 1; // silently-wrong answer: the gate must catch it
        return batch;
      },
    });
    await assert.rejects(importBatch(candidatePath, decisionsPath, opts(tree)), /fails the gate/);
    // No new bank, no new manifest, pointer untouched, ledger untouched.
    const pointer = parseActiveManifestPointer(await readJson(join(tree.resourcesDir, "question-banks", "active-manifest.json")));
    assert.equal(pointer.manifest, "question-banks/manifest.v1");
    await assert.rejects(readJson(join(tree.resourcesDir, "question-banks", "std1", "std1.bank-a.v2.json")), /ENOENT/);
    const ledger = await readJson(tree.ledgerPath);
    assert.equal(ledger.reviewed_total, 20);
  } finally {
    await rm(tree.dir, { recursive: true, force: true });
  }
});

test("import: version collision and all-rejected batches abort", async () => {
  const tree = await makeTree();
  try {
    const allRejected = await staged(tree, { seed: 707, bankId: "std1.bank-a" });
    const decisions = await readJson(allRejected.decisionsPath);
    decisions.rejected = decisions.reviewed.map((id) => ({ id, reason: "no" }));
    await writeFile(allRejected.decisionsPath, JSON.stringify(decisions));
    await assert.rejects(importBatch(allRejected.candidatePath, allRejected.decisionsPath, opts(tree)), /nothing to import/);

    const ok = await staged(tree, { seed: 708, bankId: "std1.bank-a" });
    await importBatch(ok.candidatePath, ok.decisionsPath, opts(tree));
    // The same candidate cannot import twice (its version is now taken).
    await assert.rejects(importBatch(ok.candidatePath, ok.decisionsPath, opts(tree)), /regenerate/);
  } finally {
    await rm(tree.dir, { recursive: true, force: true });
  }
});

test("import: merge into a schema-v1 bank is refused (v1 predates the v2 wire)", async () => {
  const tree = await makeTree();
  try {
    // Downgrade the routed bank to a v1-shaped artifact.
    const v1 = {
      schema_version: 1,
      bank_id: "std1.bank-a",
      version: 1,
      source: "legacy fixture",
      currency: "RM",
      questions: [
        {
          id: 1, topic: "4.2", tp_level: 2, profile: "dpk3_2026_core", answer_unit: "none",
          operation: "addition", expression: "2 + 3", answer: 5,
          question_zh: "2 + 3 = ___", question_en: "2 + 3 = ___",
          distractors: [
            { value: 4, strategy: "off-by-one-count" },
            { value: 6, strategy: "off-by-one-count" },
            { value: 1, strategy: "wrong-operation" },
          ],
        },
      ],
    };
    await writeFile(join(tree.resourcesDir, "question-banks", "std1", "std1.bank-a.v1.json"), JSON.stringify(v1, null, 2) + "\n");
    const { candidatePath, decisionsPath } = await staged(tree, { seed: 808, bankId: "std1.bank-a" });
    await assert.rejects(importBatch(candidatePath, decisionsPath, opts(tree)), /schema v1.*cannot merge/s);
  } finally {
    await rm(tree.dir, { recursive: true, force: true });
  }
});

test("rollback: repoints after verifying the whole target chain; refuses broken targets", async () => {
  const tree = await makeTree();
  try {
    const { candidatePath, decisionsPath } = await staged(tree, { seed: 909, bankId: "std1.bank-a" });
    await importBatch(candidatePath, decisionsPath, opts(tree, { activate: true }));
    let pointer = parseActiveManifestPointer(await readJson(join(tree.resourcesDir, "question-banks", "active-manifest.json")));
    assert.equal(pointer.manifest, "question-banks/manifest.v2");

    const back = await rollbackManifest("manifest.v1", opts(tree));
    assert.equal(back.manifest, "question-banks/manifest.v1");
    pointer = parseActiveManifestPointer(await readJson(join(tree.resourcesDir, "question-banks", "active-manifest.json")));
    assert.equal(pointer.manifest, "question-banks/manifest.v1");
    // And the rolled-back chain still resolves and verifies.
    const manifest = parseQuestionBankManifest(await readJson(join(tree.resourcesDir, "question-banks", "manifest.v1.json")));
    const entry = resolveManifestEntry(manifest, { grade: "std1", topic: "4.2", profile: "dpk3_2026_core", tpLevel: 2 });
    const bank = parseQuestionBankData(await readJson(join(tree.resourcesDir, `${entry.path}.json`)));
    verifyManifestEntryAgainstBank(entry, bank);

    // A target whose bank file vanished must NOT be selected.
    await assert.rejects(rollbackManifest("manifest.v9", opts(tree)), /ENOENT/);
    pointer = parseActiveManifestPointer(await readJson(join(tree.resourcesDir, "question-banks", "active-manifest.json")));
    assert.equal(pointer.manifest, "question-banks/manifest.v1");
  } finally {
    await rm(tree.dir, { recursive: true, force: true });
  }
});
